# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_person_best_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
