# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_fear'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fears',
            field=models.ManyToManyField(to='my_app.Fear'),
        ),
    ]
