# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('calories', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='special',
            name='ingredients',
            field=models.ManyToManyField(to='menu_api.Ingredient'),
        ),
    ]
